server:
    port: 8181
    tomcat.uri-encoding: UTF-8

# SPRING PROFILES
spring:
#    http:
##        encoding.charset: UTF-8
#        encoding.enable: true
##        encoding.force: true
#    jackson:
#        date-format: yyyy-MM-dd HH:mm:ss
#        time-zone: GMT+8
    datasource:
        url: jdbc:mysql://118.89.151.100:3306/caipiao?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
        #    url: jdbc:mysql://192.168.99.36:3306/visualize?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    ##指定了freemarker文件的路径是classpath/templates，在resources文件夹下的
    ##templates新建freemarker文件夹，并且在其中新建index.ftl（上面配置文件中已经指定了freemarker模板的文件后缀为ftl）：
    freemarker:
        template-loader-path: classpath:/templates
        charset: utf-8
        cache: false
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
# 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
#    spring.freemarker.allow-request-override=false
#  # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
#    spring.freemarker.allow-session-override=false
#  # 是否启用模板缓存。
#    spring.freemarker.cache=false
#  # 模板编码。
#    spring.freemarker.charset=UTF-8
#  # 是否检查模板位置是否存在。
#    spring.freemarker.check-template-location=true
#  # Content-Type value.
#    spring.freemarker.content-type=text/html
#  # 是否启用freemarker
#    spring.freemarker.enabled=true
#  # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
#    spring.freemarker.expose-request-attributes=false
#  # 是否在merge模板的时候，将HttpSession属性都添加到model中
#    spring.freemarker.expose-session-attributes=false
#  # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
#    spring.freemarker.expose-spring-macro-helpers=true
#  # 是否优先从文件系统加载template，以支持热加载，默认为true
#    spring.freemarker.prefer-file-system-access=true
#  # 设定模板的后缀.
#    spring.freemarker.suffix=.ftl
#  # 设定模板的加载路径，多个以逗号分隔，默认:
#    spring.freemarker.template-loader-path=classpath:/templates/
#  # 设定FreeMarker keys.
#    spring.freemarker.settings.template_update_delay=0
#    spring.freemarker.settings.default_encoding=UTF-8
#    spring.freemarker.settings.classic_compatible=true


mybatis:
#     mapperLocations: classpath:mapper/*.xml
     config-location: classpath:mybatis/mybatis-config.xml
     mapper-locations: classpath:mybatis/mapper/*.xml
     type-aliases-package: com.battle.panda.caipiao.dao




